Sample didn't work in Chrome 51 anymore. Updated spring dependencies to fix it. This caused a java.lang.NoSuchMethodError from an older alpn lib, so added the latest version. Updated documentation accordingly.